#!/usr/bin/perl

# mark
# by figiel.

# use with bash.
#
# setup a function first (add below to bashrc):
#
# go() { cd `mark get $*`; }
#

use Cwd;

dbmopen(%mark_db, $ENV{"HOME"} . "/.mark.db", 0666);
my $db   = \%mark_db;
my $cmd  = shift @ARGV;
my $args = join " ", @ARGV;

if ( $cmd eq "set" ) {
    $db->{$args} = getcwd if length $args;
}
elsif ( $cmd eq "list" ) {
    foreach my $key ( keys %$db ) {
        print "[$key] = " . ( $db->{$key} ) . "\n";
    }
}
elsif ( $cmd eq "get" ) {
    if ( defined $args && defined $db->{$args} ) {
        print $db->{$args};
    }
    elsif ( length $args ) {
        foreach my $key ( keys %$db ) {
            if ( $key =~ /^$args/ ) {
                print $db->{$key};
                exit 0;
            }
        }
    }
}
elsif ( $cmd eq "clear" ) {
    delete $db->{$args};
}
elsif ( length $cmd ) {
    $db->{$cmd} = getcwd;
}
