#!/usr/bin/perl

# mark
# by figiel.

# use with bash.
#
# setup a function first (add below to bashrc):
#
# go() { cd `mark get $*`; }
#
# requires libdbm-deep-perl
#

use lib $ENV{'HOME'} . "/perl5";

use DBM::Deep;
use Cwd;

my $db   = DBM::Deep->new( $ENV{"HOME"} . "/.dirmarks.db" );
my $cmd  = shift @ARGV;
my $args = join " ", @ARGV;

if ( $cmd eq "set" ) {
    $db->{$args} = getcwd if length $args;
}
elsif ( $cmd eq "list" ) {
    foreach my $key ( keys %$db ) {
        print "[$key] = " . ( $db->{$key} ) . "\n";
    }
}
elsif ( $cmd eq "get" ) {
    if ( defined $args && $db->exists($args) ) {
        print $db->{$args};
    }
    elsif ( length $args ) {
        foreach my $key ( keys %$db ) {
            if ( $key =~ /^$args/ ) {
                print $db->{$key};
                return;
            }
        }
    }
}
elsif ( $cmd eq "clear" ) {
    delete $db->{$args};
}
elsif ( length $cmd ) {
    $db->{$cmd} = getcwd;
}
